name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  freezed: ^3.0.6
  import_sorter: ^4.6.0
  talker: ^4.7.1
  talker_dio_logger: ^4.7.1
  talker_bloc_logger: ^4.7.1
  path_provider: ^2.1.5
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  sqlite3: ^2.7.5
  sqlite3_flutter_libs: ^0.5.32
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  drift_dev: ^2.26.0

flutter:
  uses-material-design: true
